version: '3.4'

services:
  rest:
    network_mode: host
    build:
      context: rest/
    image: rest_rabbitmq
  dialer:
    network_mode: host
    build:
      context: dialer/
    image: dialer_rabbitmq
    volumes:
      - /usr/share/asterisk/sounds/ru/t2s:/usr/share/asterisk/sounds/ru/t2s
    ports:
      - "3333:3333"
  rpc:
    network_mode: host
    build:
      context: rpc/
    image: rpc_rabbitmq
    volumes:
      - /usr/share/asterisk/sounds/ru/t2s:/usr/share/asterisk/sounds/ru/t2s
